version: '3'
services:
  web:
    build: .
    image: gcr.io/instant-text-434604-i1/myapp:latest
    ports:
      - "1337:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: todolist
      MYSQL_USER: root
      MYSQL_PASSWORD: pswd123
    volumes:
      - web_data:/var/www/html

  db:
    container_name: mysql57
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pswd123
      MYSQL_DATABASE: todolist
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  web_data:
